void ControllerReboot();
void DisplayFadeIn();
void DisplayFadeOut();
void FanControl();
void SendPowerSignal(int Duration);
void PowerCommand(String Command);
bool isOfflineTime();
bool isNightModeTime();
void NightModeRoutine();
void LEDBrightnessControl(int PreviousBrightness, int CurrentBrightness);
void ControllerRebootRoutine();
void Debugger();
bool Pinger(bool Enforce);
void WiFiState();
void StateUpdate();
void AnnounceState(uint8_t State);
void AutoController(int State);
void drawIcon(int x, int y, int color, int icon[12][12]);
void ScreenOne();
void ScreenTwo();
void ScreenThree();
void ShowMetrics();
void HandleMQTT();
void TimeUpdate();
void GetMetrics(char* topic, byte* payload, unsigned int length);
